#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies2_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies2_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p hi
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
