#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies8_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies8_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p bigmemh
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
