#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies4_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies4_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p bigmemhi
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
