#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p serial
#SBATCH --array=0-86
#SBATCH --ntasks=32
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly1_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly20_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly21_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly22_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly23_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly24_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly25_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly26_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly27_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly28_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly38_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly39_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly3_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly40_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly41_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly42_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly43_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly44_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly45_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly46_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly74_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly75_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly76_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly77_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly78_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly79_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly7_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly80_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly81_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly82_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly83_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly83_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly83_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly83_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly83_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly83_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly84_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly84_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly84_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly84_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly84_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly84_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly85_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly85_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly85_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly85_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly85_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly85_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly8_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly8_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly8_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly8_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly8_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly8_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly9_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly9_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly9_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly9_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly9_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly9_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
