#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies7_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies7_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p serial
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly65_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly66_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly67_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly68_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly69_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly6_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly70_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly71_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly72_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly73_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
