#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies6_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies6_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p med
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly56_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly57_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly58_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly59_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly5_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly60_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly61_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly62_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly63_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly64_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
