#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies3_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies3_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p bigmemm
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly29_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly2_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly30_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly31_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly32_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly33_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly34_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly35_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly36_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly37_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
