#!/bin/bash -l
#SBATCH -D /home/makman/ProExp/trimmomatic
#SBATCH -J Trim4
#SBATCH -o /home/makman/ProExp/outs/trimmomatic_ALMA4_stdout.txt
#SBATCH -e /home/makman/ProExp/outs/trimmomatic_ALMA4_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p bigmemh
#SBATCH --ntasks=64

module load java
java -jar ./trimmomatic-0.33.jar SE /home/makman/ProExp/Rawseq/ALMA4/ALMA4_combined.fastq ALMA4_combined_trimmed.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
