#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies5_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies5_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p bigmeml
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly47_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly48_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly49_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly4_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly50_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly51_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly52_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly53_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly54_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly55_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
