#!/bin/bash -l
#SBATCH -D /home/makman/Pellies/trim
#SBATCH -J Trim
#SBATCH -o /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies1_stdout.txt
#SBATCH -e /home/makman/Pellies/outs/trimmomaticafterdemultiplex_Pellies1_stderr.txt
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@ucdavis.edu
#SBATCH -p serial
#SBATCH --array=0-9
#SBATCH --ntasks=16
module load java
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly10_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly11_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly12_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly13_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly14_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly15_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly16_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly17_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly18_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
java -jar ./trimmomatic-0.33.jar PE -threads 64 /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_F_trimmed_unpaired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R_trimmed_paired.fastq /home/makman/Pellies/Demultiplexed/notrim/Pelly19_R_trimmed_unpaired.fastq ILLUMINACLIP:adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
